# Create a GitHub action to email a report from a file at 6 a.m. daily.
name: Email Report
on:
  schedule:
    - cron: '0 6 * * *'
jobs:
  email:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Email report
        uses: dawidd6/action-send-mail@v2
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          subject: Daily Report
          body: The daily report is attached.
          to: ${{ secrets.RECIPIENT }}
          attachments: daily-report.txt